#ifndef TYPES_H
#define TYPES_H

namespace TYPES
{
    enum
    {
        INCONNU, BINOMIAL, QUALITATIF_PURE, QUALITATIF_ORDINAL, QUANTITATIF_DISCRET, QUANTITATIF_CONTINU_PURE, QUANTITATIF_CONTINU_BORNE
    };
}

#endif // TYPES_H
